[book]
authors = ["Akashiya-Chime"]
language = "zh"
multilingual = false
src = "src"
title = "UNGEE-Notebook"

[output.html]
git-repository-url = "https://github.com/Akashiya-Chime/Notebook-for-UNGEE"
git-repository-icon = "fa-github"
mathjax-support = true
site-url = "https://akashiya-chime.github.io/Notebook-for-UNGEE/"

[output.html.fold]
enable = true
level = 0